// <auto-generated />
using System;
using Kolokwium2.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kolokwium2.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240614103210_crate tables with test data part 2")]
    partial class cratetableswithtestdatapart2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0-preview.5.24306.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kolokwium2.Models.BackpackSlot", b =>
                {
                    b.Property<int>("BackpackSlotPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BackpackSlotPK"));

                    b.Property<int>("CharacterFK")
                        .HasColumnType("int")
                        .HasColumnName("FK_character");

                    b.Property<int>("ItemFK")
                        .HasColumnType("int")
                        .HasColumnName("FK_item");

                    b.HasKey("BackpackSlotPK");

                    b.HasIndex("CharacterFK");

                    b.HasIndex("ItemFK");

                    b.ToTable("Backpack_Slots");

                    b.HasData(
                        new
                        {
                            BackpackSlotPK = 1,
                            CharacterFK = 1,
                            ItemFK = 1
                        },
                        new
                        {
                            BackpackSlotPK = 2,
                            CharacterFK = 1,
                            ItemFK = 2
                        });
                });

            modelBuilder.Entity("Kolokwium2.Models.Character", b =>
                {
                    b.Property<int>("CharacterPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CharacterPK"));

                    b.Property<int>("CharacterCurrentWeight")
                        .HasColumnType("int")
                        .HasColumnName("current_weig");

                    b.Property<string>("CharacterFirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("CharacterLastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<int>("CharacterMaxWeight")
                        .HasColumnType("int")
                        .HasColumnName("max_weight");

                    b.Property<int>("CharacterMoney")
                        .HasColumnType("int")
                        .HasColumnName("money");

                    b.HasKey("CharacterPK");

                    b.ToTable("Characters");

                    b.HasData(
                        new
                        {
                            CharacterPK = 1,
                            CharacterCurrentWeight = 100,
                            CharacterFirstName = "Siwy",
                            CharacterLastName = "Geralt",
                            CharacterMaxWeight = 300,
                            CharacterMoney = 100
                        },
                        new
                        {
                            CharacterPK = 2,
                            CharacterCurrentWeight = 0,
                            CharacterFirstName = "TestFirstName",
                            CharacterLastName = "TestLastName",
                            CharacterMaxWeight = 300,
                            CharacterMoney = 150
                        },
                        new
                        {
                            CharacterPK = 3,
                            CharacterCurrentWeight = 0,
                            CharacterFirstName = "TestFirstName2",
                            CharacterLastName = "TestLastName2",
                            CharacterMaxWeight = 400,
                            CharacterMoney = 200
                        });
                });

            modelBuilder.Entity("Kolokwium2.Models.CharacterTitle", b =>
                {
                    b.Property<int>("CharacterFK")
                        .HasColumnType("int")
                        .HasColumnName("FK_character");

                    b.Property<int>("TitleFK")
                        .HasColumnType("int")
                        .HasColumnName("FK_title");

                    b.Property<DateTime>("CharacterTitleAquireAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("aquire_at");

                    b.HasKey("CharacterFK", "TitleFK");

                    b.HasIndex("TitleFK");

                    b.ToTable("Characters_Titles");

                    b.HasData(
                        new
                        {
                            CharacterFK = 1,
                            TitleFK = 1,
                            CharacterTitleAquireAt = new DateTime(2024, 6, 14, 12, 32, 9, 898, DateTimeKind.Local).AddTicks(5070)
                        },
                        new
                        {
                            CharacterFK = 1,
                            TitleFK = 2,
                            CharacterTitleAquireAt = new DateTime(2024, 6, 14, 12, 32, 9, 915, DateTimeKind.Local).AddTicks(5470)
                        });
                });

            modelBuilder.Entity("Kolokwium2.Models.Item", b =>
                {
                    b.Property<int>("ItemPK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemPK"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<int>("ItemWeight")
                        .HasColumnType("int")
                        .HasColumnName("weig");

                    b.HasKey("ItemPK");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemPK = 1,
                            ItemName = "Miecz na potwory",
                            ItemWeight = 50
                        },
                        new
                        {
                            ItemPK = 2,
                            ItemName = "TestItem2",
                            ItemWeight = 20
                        },
                        new
                        {
                            ItemPK = 3,
                            ItemName = "TestItem3",
                            ItemWeight = 30
                        });
                });

            modelBuilder.Entity("Kolokwium2.Models.Title", b =>
                {
                    b.Property<int>("TitlePK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TitlePK"));

                    b.Property<string>("TitleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("TitlePK");

                    b.ToTable("Titles");

                    b.HasData(
                        new
                        {
                            TitlePK = 1,
                            TitleName = "Biały Wilk"
                        },
                        new
                        {
                            TitlePK = 2,
                            TitleName = "Gwynbleidd"
                        },
                        new
                        {
                            TitlePK = 3,
                            TitleName = "TestTitle3"
                        });
                });

            modelBuilder.Entity("Kolokwium2.Models.BackpackSlot", b =>
                {
                    b.HasOne("Kolokwium2.Models.Character", "Character")
                        .WithMany("BackpackSlots")
                        .HasForeignKey("CharacterFK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Kolokwium2.Models.Item", "Item")
                        .WithMany("BackpackSlots")
                        .HasForeignKey("ItemFK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Kolokwium2.Models.CharacterTitle", b =>
                {
                    b.HasOne("Kolokwium2.Models.Character", "Character")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("CharacterFK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Kolokwium2.Models.Title", "Title")
                        .WithMany("CharacterTitles")
                        .HasForeignKey("TitleFK")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Title");
                });

            modelBuilder.Entity("Kolokwium2.Models.Character", b =>
                {
                    b.Navigation("BackpackSlots");

                    b.Navigation("CharacterTitles");
                });

            modelBuilder.Entity("Kolokwium2.Models.Item", b =>
                {
                    b.Navigation("BackpackSlots");
                });

            modelBuilder.Entity("Kolokwium2.Models.Title", b =>
                {
                    b.Navigation("CharacterTitles");
                });
#pragma warning restore 612, 618
        }
    }
}
